theme: minima

title: Multimorbidity in Allergic Conditions
description: A website to store information about the multimorbidity in allergic condtions project. Information on study background, methods, progress, methods, etc. [Meet the team](pages/team.html)

#logo: [Location of the logo]
#show_downloads: ["true" or "false" to indicate whether to provide a download URL] 
#google_analytics: [Your Google Analytics tracking ID]
