title: Multimorbidity in Common Allergic Conditions
name: Alasdair Henderson
email: alasdair.henderson1@lshtm.ac.uk
description: > # this means to ignore newlines until "show_excerpts:"
 A website to store information about the multimorbidity in allergic condtions project. 
 Information on study background, results, and how to get involved.
show_excerpts: false # set to true to show excerpts on the homepage

# generate social links in footer
#social_links
twitter_username: hendersonad
github_username:  a-henderson91
    
# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - pages/summary.md
 - pages/team.md
 - pages/paper.md
 - pages/ppi.md
 

# Build settings
theme: jekyll-theme-cayman


plugins:
 - jekyll-feed
 - jekyll-seo-tag
